### ISSUE TITLE
Questions about evaluating the generated model

### ISSUE THREAD

**Issue by nbzxf** [BMDSoftware/neji#12]
How to evaluate the generated model using the "evaluate.sh" in Neji-master ? Can anyone give an example? (Gold files in BC2 format and silver files in JSON format)Thanks

**Comment by davidcampos** [comment]
@nbzxf 
To use the `evaluate.sh` script, both gold and silver corpus should be in A1 format.

To evaluate NER annotations:
`./evaluate.sh -g <folder_with_gold_a1_files> -s <folder_with_silver_a1_files> -tner all`

To evaluate NER annotations with identifiers:
`./evaluate.sh -g <folder_with_gold_a1_files> -s <folder_with_silver_a1_files> -tnorm all`

Multiple evaluation matches are used:
- **Exact**: annotation is accepted if both left and right sides match with the gold standard annotation;
- **Left**: annotation is accepted if the left side matches;
- **Right**: annotation is accepted if the right side matches;
- **Shared**: annotation is accepted if the left or the right sides match;
- **Overlap**: annotation is accepted if there is any kind of match: exact, nested or intersected.

**Comment by nbzxf** [comment]
@davidcampos 
Thanks for your reply. ^_^
