### ISSUE TITLE
Carriage return characters in neji.sh cause error when running on UNIX based system in neji 2.0.1 distribution 

### ISSUE THREAD

**Issue by JohnGiorgi** [BMDSoftware/neji#13]
Running `neji.sh` from neji 2.0.1 distribution on a UNIX operating system results in the following error: `-bash: ./neji.sh: /bin/bash^M: bad interpreter: No such file or directory`.

This can be resolved by running `dos2unix -k -o /path/to/neji.sh` after installing `dos2unix` (if not already installed)

**Comment by davidcampos** [comment]
@JohnGiorgi 
Thanks for the feedback. The release was updated after executing the "dos2unix" command on "neji.sh", "nejiTrain.sh" and "nejiWeb.sh" files.
