### ISSUE TITLE
Problem when using models created according to WIKI specifications

### ISSUE THREAD

**Issue by lucasaas98** [BMDSoftware/neji#20]
**Describe the bug**
When attempting to run an NER model using the steps presented in the wiki I get:
`pt.ua.tm.neji.exception.NejiException: There was a problem loading the model files.` 
Which seems to be caused by: `java.util.zip.ZipException: Not in GZIP format`

**To Reproduce**

1. Create a maven project and add the Neji repository to the pom.xml _(Screenshot 1)_
2. Go to the Wiki page 'SDK Train' and copy the code adapting filenames. _(Screenshot 2)_
3. Copy the config file present in "example/train" to the project. _(Screenshot 3)_
4. Train a model _(Screenshot 4)_
5. Create a properties file with the adapted names used in step 2. _(Screenshot 5)_
6. Go to the Wiki page 'SDK Annotate' and copy the code snippet to annotate a single document adapting filenames _(Screenshot 6)_
7. Run the annotation code.
8. Get the aforementioned error. _(Screenshot 7)_

The whole project is running on the Springboot platform.

**Expected behavior**
The document should be annotated using the model and the dictionaries provided. 

**Screenshots**

_Screenshot 1_ - pom.xml
![image](https://user-images.githubusercontent.com/44382228/114568482-10f7ac00-9c6c-11eb-839c-2d4ad8fa3bf2.png)

_Screenshot 2_ - Trainer.java
![image](https://user-images.githubusercontent.com/44382228/114569162-a5620e80-9c6c-11eb-9791-388f1cee0da9.png)

_Screenshot 3_ - model.config
![image](https://user-images.githubusercontent.com/44382228/114570272-9af44480-9c6d-11eb-99d5-0610bb567ce9.png)

_Screenshot 4_ - Terminal after training the model
![image](https://user-images.githubusercontent.com/44382228/114569379-d4788000-9c6c-11eb-8b8c-fdf73297fb3b.png)

_Screenshot 5_ - model.properties
![image](https://user-images.githubusercontent.com/44382228/114570440-bc553080-9c6d-11eb-98b9-9246c74dfd96.png)

_Screenshot 6_ - Annotater.java
This version is slightly modified when compared to the wiki one.
![image](https://user-images.githubusercontent.com/44382228/114569808-33d69000-9c6d-11eb-9164-2a8e21f4ba6c.png)

_Screenshot 7_ - Terminal after getting the error
![image](https://user-images.githubusercontent.com/44382228/114570591-d989ff00-9c6d-11eb-84b4-71111cd11fad.png)

**Environment:**
- OS: Pop!_OS
- Kernel 5.11.0-7612-generic
- Openjdk 11.0.10
- Apache Maven 3.6.3

**Additional context**
To make sure the problem wasn't derived from using a version of java that is not compatible I also dockerized my application to use Java 8 but the problem was still replicable there. 
I have also tried using a combination of parameters for both the config file and the properties file but I seem to land on the same error.

**Comment by aleixomatos** [comment]
Hi,
Could you try this:

model.write(new GZIPOutputStream(new FileOutputStream(modelFile)));

**Comment by lucasaas98** [comment]
That fixed the problem. Thanks for the help!
